### ISSUE TITLE
生成的epub中没有内容

### ISSUE THREAD

**Issue by MerrickZ** [zzZ5/Html2Epub#1]
使用html文件方式添加chapter以后
生成的epub文件目录正常，
但是内容都是```<p></p>```
一点文字都没有

**Comment by zzZ5** [comment]
最近比较忙，具体是哪个网页，有空我看看

**Comment by MerrickZ** [comment]
我已经搞定了
问题是这样的，如果有以下形式的html:
```
<body>
这里是内容
<p></p>
这里有内容
</body>
```
也就是说，在body标签里的文本内容存在的话，或者这些文本在```<pre>```标签里的时候，就会丢失。
应该是clean的过程中出的问题，没有对这类文本进行识别。

目前我的解决办法是
手动给文本加<p></p>

**Comment by zzZ5** [comment]
[kindle中所支持的tag](https://kdp.amazon.com/help?topicId=A1JPUWCSD6F59O)
clean是按照这个标准来识别的，若是需要支持`<pre>`等标签，可以在 constants.py 里 SUPPORTED_TAGS字典中添加需要识别的标签名。

**Comment by MerrickZ** [comment]
嗯，这个网页没有标签。。看来要加body标签了

baoju <notifications@github.com> 于 2019年9月10日周二 下午12:02写道：
